# Generated by Django 2.0.7 on 2018-07-09 12:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_db_constraints.operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='ms', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('excpression', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=12)),
                ('priority', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^[\\-a-zA-Z0-9]*$')])),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4')),
                ('login', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera_goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Camera_zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Component_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Action')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Infrasctructure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=2)),
                ('no', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)])),
                ('max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recognition_goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('complexity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^[\\-a-zA-Z0-9]*$')])),
                ('max_human_silhouettes_no', models.PositiveIntegerField()),
                ('origin_camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Zone_alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Alert')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Zone_goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Recognition_goal')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Zone_polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Zone')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='infrasctructure',
            unique_together={('type', 'no')},
        ),
        migrations.AddField(
            model_name='camera_zone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Zone'),
        ),
        migrations.AddField(
            model_name='camera_goal',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Recognition_goal'),
        ),
        migrations.AddField(
            model_name='alert',
            name='component_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Component_action'),
        ),
        migrations.AlterUniqueTogether(
            name='zone_polygon',
            unique_together={('zone', 'point_no')},
        ),
        migrations.AlterUniqueTogether(
            name='zone_goal',
            unique_together={('zone', 'goal')},
        ),
        migrations.AlterUniqueTogether(
            name='camera_goal',
            unique_together={('camera', 'goal')},
        ),
        django_db_constraints.operations.AlterConstraints(
            name='Infrasctructure',
            db_constraints={'no_range': 'check (no >=1 AND no <=24 )', 'value_range': 'check (value >=0.0 AND value <=1.0 )'},
        ),
        django_db_constraints.operations.AlterConstraints(
            name='Zone_polygon',
            db_constraints={'point_values': 'check (point_no >=1)'},
        ),
    ]
