# Generated by Django 2.1b1 on 2018-07-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone_polygon',
            name='id',
        ),
        migrations.AlterField(
            model_name='zone_polygon',
            name='point_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
