# Generated by Django 2.1b1 on 2018-07-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0002_auto_20180725_0837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actions',
            new_name='Available_action',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='actions',
            new_name='action',
        ),
    ]
