# Generated by Django 2.1b1 on 2018-07-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0002_auto_20180709_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zone_polygon',
            unique_together={('x', 'y')},
        ),
    ]
