# Generated by Django 2.1b1 on 2018-07-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0003_auto_20180709_1629'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zone_polygon',
            unique_together={('x', 'y', 'zone')},
        ),
    ]
