# Generated by Django 2.1b1 on 2018-07-25 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0003_auto_20180725_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='SVS_output',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('output_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='action',
        ),
        migrations.DeleteModel(
            name='Available_action',
        ),
        migrations.AddField(
            model_name='action',
            name='svs_output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output', to='svs.SVS_output'),
        ),
    ]
