# Generated by Django 2.1b1 on 2018-07-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0004_auto_20180709_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.SlugField(max_length=12, unique=True),
        ),
    ]
