# Generated by Django 2.1b1 on 2018-07-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0004_auto_20180725_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component_action',
            name='action',
        ),
        migrations.RemoveField(
            model_name='component_action',
            name='component',
        ),
        migrations.AddField(
            model_name='action',
            name='component',
            field=models.ManyToManyField(to='svs.SVS_output'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='component_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.Action'),
        ),
        migrations.DeleteModel(
            name='Component_action',
        ),
    ]
