# Generated by Django 2.1b1 on 2018-07-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0005_auto_20180710_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.SlugField(max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('name', 'origin_camera')},
        ),
    ]
