# Generated by Django 2.1b1 on 2018-07-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0006_auto_20180725_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='svs_output',
        ),
        migrations.AddField(
            model_name='action',
            name='svs_output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output', to='svs.SVS_output'),
        ),
        migrations.RemoveField(
            model_name='alert',
            name='component_action',
        ),
        migrations.AddField(
            model_name='alert',
            name='component_action',
            field=models.ManyToManyField(to='svs.Action'),
        ),
    ]
