# Generated by Django 2.1b1 on 2018-07-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0007_auto_20180725_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svs_output',
            name='output_id',
        ),
        migrations.AddField(
            model_name='svs_output',
            name='description',
            field=models.CharField(default='silnik', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='svs_output',
            name='svs_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
