# Generated by Django 2.1b1 on 2018-07-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0007_test'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='camera_goal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='camera_goal',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='camera_goal',
            name='goal',
        ),
        migrations.DeleteModel(
            name='Camera_goal',
        ),
    ]
