# Generated by Django 2.1b1 on 2018-07-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0008_auto_20180711_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.SlugField(max_length=12),
        ),
    ]
