# Generated by Django 2.1b1 on 2018-07-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0009_auto_20180711_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='max_human_silhouettes_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
