# Generated by Django 2.1b1 on 2018-07-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0010_auto_20180711_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera_zone',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='camera_zone',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Camera_zone',
        ),
    ]
