# Generated by Django 2.1b1 on 2018-07-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0010_auto_20180725_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='svs_task',
            name='description',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
