# Generated by Django 2.1b1 on 2018-07-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0011_auto_20180712_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_model', models.CharField(max_length=100)),
                ('custom_camera_url', models.URLField(blank=True, null=True)),
                ('camera', models.ForeignKey(null=True, on_delete='SET_NULL', to='svs.Camera')),
            ],
        ),
    ]
