# Generated by Django 2.1b1 on 2018-07-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0011_svs_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARM_output',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=20, null=True)),
                ('arm_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ARM_task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=20, null=True)),
                ('arm_task', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='svs_output',
        ),
        migrations.RemoveField(
            model_name='action',
            name='svs_task',
        ),
        migrations.DeleteModel(
            name='SVS_output',
        ),
        migrations.DeleteModel(
            name='SVS_task',
        ),
        migrations.AddField(
            model_name='action',
            name='arm_output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output', to='svs.ARM_output'),
        ),
        migrations.AddField(
            model_name='action',
            name='arm_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task', to='svs.ARM_task'),
        ),
    ]
