# Generated by Django 2.1b1 on 2018-07-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0012_auto_20180726_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arm_output',
            name='arm_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
