# Generated by Django 2.1b1 on 2018-07-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0012_camera_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera_type',
            name='camera',
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='svs.Camera_type'),
        ),
    ]
