# Generated by Django 2.1b1 on 2018-07-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0013_auto_20180718_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera_type',
            name='custom_camera_url',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
