# Generated by Django 2.1b1 on 2018-07-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0014_auto_20180718_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera_type',
            name='custom_camera_url',
            field=models.URLField(help_text='Use {admin} and {password} for creditentials'),
        ),
    ]
