# Generated by Django 2.1b1 on 2018-07-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0015_auto_20180718_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone_alert',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='zone_alert',
            name='zone',
        ),
        migrations.AddField(
            model_name='alert',
            name='zone',
            field=models.ManyToManyField(to='svs.Zone'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_types', to='svs.Camera_type'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='origin_camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='svs.Camera'),
        ),
        migrations.AlterField(
            model_name='zone_goal',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='svs.Recognition_goal'),
        ),
        migrations.AlterField(
            model_name='zone_goal',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='svs.Zone'),
        ),
        migrations.AlterField(
            model_name='zone_polygon',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='svs.Zone'),
        ),
        migrations.DeleteModel(
            name='Zone_alert',
        ),
    ]
