# Generated by Django 2.1b1 on 2018-07-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0016_auto_20180719_1237'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zone_goal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='zone_goal',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='zone_goal',
            name='zone',
        ),
        migrations.AddField(
            model_name='recognition_goal',
            name='zone',
            field=models.ManyToManyField(to='svs.Zone'),
        ),
        migrations.DeleteModel(
            name='Zone_goal',
        ),
    ]
