# Generated by Django 2.1b1 on 2018-07-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0017_auto_20180719_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognition_goal',
            name='agregator',
            field=models.CharField(default='human_counter', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recognition_goal',
            name='zone',
            field=models.ManyToManyField(related_name='goals', to='svs.Zone'),
        ),
    ]
