# Generated by Django 2.0.7 on 2018-07-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180709_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrasctructure',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
