# Generated by Django 2.0.7 on 2018-07-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180709_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='login',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
