# Generated by Django 2.0.7 on 2018-07-09 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180709_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric', regex='/^\\S+$/')]),
        ),
    ]
