# Generated by Django 2.0.7 on 2018-07-09 11:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180709_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='camera_goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recognition_goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('complexity', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^[\\-a-zA-Z0-9]*$')]),
        ),
        migrations.AddField(
            model_name='camera_goal',
            name='camera_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Camera'),
        ),
        migrations.AddField(
            model_name='camera_goal',
            name='goal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Recognition_goal'),
        ),
    ]
