# Generated by Django 2.0.7 on 2018-07-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180709_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera_goal',
            old_name='camera_id',
            new_name='camera',
        ),
        migrations.RenameField(
            model_name='camera_goal',
            old_name='goal_id',
            new_name='goal',
        ),
    ]
