# Generated by Django 2.0.7 on 2018-07-09 12:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_db_constraints.operations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180709_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='ms', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('excpression', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=12)),
                ('priority', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Camera_zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Camera')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Component_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Action')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Zone_alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Alert')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Zone_goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Recognition_goal')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Zone_polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Zone')),
            ],
        ),
        migrations.AlterField(
            model_name='infrasctructure',
            name='no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='alert',
            name='component_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Component_action'),
        ),
        migrations.AlterUniqueTogether(
            name='zone_goal',
            unique_together={('zone', 'goal')},
        ),
        django_db_constraints.operations.AlterConstraints(
            name='Zone_polygon',
            db_constraints={'point_values': 'check (point_no >=1)'},
        ),
    ]
