# Generated by Django 2.0.7 on 2018-07-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180709_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='action',
        ),
        migrations.AddField(
            model_name='component',
            name='name',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
    ]
