# Generated by Django 2.0.7 on 2018-07-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180709_1415'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zone_polygon',
            unique_together={('zone', 'point_no')},
        ),
    ]
