# Generated by Django 2.0.7 on 2018-07-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20180709_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='component_action',
        ),
        migrations.AlterUniqueTogether(
            name='camera_goal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='camera_goal',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='camera_goal',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='camera_zone',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='camera_zone',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='component_action',
            name='action',
        ),
        migrations.RemoveField(
            model_name='component_action',
            name='component',
        ),
        migrations.DeleteModel(
            name='Infrasctructure',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='origin_camera',
        ),
        migrations.RemoveField(
            model_name='zone_alert',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='zone_alert',
            name='zone',
        ),
        migrations.AlterUniqueTogether(
            name='zone_goal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='zone_goal',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='zone_goal',
            name='zone',
        ),
        migrations.AlterUniqueTogether(
            name='zone_polygon',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='zone_polygon',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='camera_goal',
        ),
        migrations.DeleteModel(
            name='Camera_zone',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Component_action',
        ),
        migrations.DeleteModel(
            name='Recognition_goal',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.DeleteModel(
            name='Zone_alert',
        ),
        migrations.DeleteModel(
            name='Zone_goal',
        ),
        migrations.DeleteModel(
            name='Zone_polygon',
        ),
    ]
